# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import utils.widgets
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsReceivableInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('status', models.CharField(help_text='e.g., age, factored, other', max_length=32)),
                ('name', models.CharField(default='', max_length=128, blank=True)),
                ('date_due', models.DateField(null=True)),
                ('contract_number', models.CharField(help_text='Invoice Number or Government Grant or Contract Number', max_length=64, blank=True)),
                ('street', models.CharField(default='', max_length=128, blank=True)),
                ('city', models.CharField(default='', max_length=64, blank=True)),
                ('state_name', models.CharField(default='', choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('PUER', 'Puerto Rico')], verbose_name='State', max_length=64, blank=True)),
                ('zipcode', models.CharField(default='', verbose_name='Zip', max_length=10, blank=True)),
                ('amount_due', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AssetTransferDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('assetlist', models.CharField(verbose_name='List Asset(s)', max_length=128)),
                ('value', models.PositiveIntegerField(default=0, verbose_name='Value at Time of Transfer')),
                ('date', models.DateField(verbose_name='Date Transferred')),
                ('recipient', models.CharField(verbose_name='To Whom or Where was it Transferred', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('account_type', models.CharField(max_length=32)),
                ('bank_name', models.CharField(max_length=128)),
                ('street', models.CharField(default='', max_length=128, blank=True)),
                ('city', models.CharField(default='', max_length=64, blank=True)),
                ('state_name', models.CharField(default='', choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('PUER', 'Puerto Rico')], verbose_name='State', max_length=64, blank=True)),
                ('zipcode', models.CharField(default='', verbose_name='Zip', max_length=10, blank=True)),
                ('account_number', models.CharField(max_length=32)),
                ('account_balance', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BankruptcyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('filed', models.DateField(verbose_name='Date Filed')),
                ('dismissed', models.DateField(verbose_name='Date Dismissed', null=True, blank=True)),
                ('discharged', models.DateField(verbose_name='Date Discharged', null=True, blank=True)),
                ('petition_number', models.CharField(verbose_name='Petition Number', max_length=16)),
                ('location', models.CharField(verbose_name='Location', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('place', models.CharField(verbose_name='Place where recorded', max_length=128)),
                ('ein', models.CharField(verbose_name='Employer Identification Number (EIN)', max_length=32)),
                ('name', models.CharField(verbose_name='Name of the trust, estate, or policy', max_length=128)),
                ('amount', models.PositiveIntegerField(verbose_name='Anticipated amount to be received')),
                ('whenreceive', models.DateField(verbose_name='When will the amount be received', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessAssetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('market_value', models.PositiveIntegerField(default=0, verbose_name='Current Fair Market Value')),
                ('current_loan_balance', models.PositiveIntegerField(default=0)),
                ('lender_name', models.CharField(default='', max_length=128, blank=True)),
                ('lender_street', models.CharField(default='', max_length=128, blank=True)),
                ('lender_city', models.CharField(default='', max_length=64, blank=True)),
                ('lender_state_name', models.CharField(default='', choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('PUER', 'Puerto Rico')], verbose_name='Lender State', max_length=64, blank=True)),
                ('lender_zipcode', models.CharField(default='', verbose_name='Lender Zip', max_length=10, blank=True)),
                ('lender_phone', utils.widgets.PhoneNumberField(default='', verbose_name='Lender Phone', max_length=20, blank=True)),
                ('monthly_payment', models.PositiveIntegerField(default=0)),
                ('purchase_date', models.DateField(verbose_name='Purchase Lease Date')),
                ('final_payment_date', models.DateField(default=None, verbose_name='Date of final payment', null=True, blank=True)),
                ('description', models.CharField(verbose_name='Property Description', max_length=128)),
                ('location_street', models.CharField(default='', max_length=128, blank=True)),
                ('location_city', models.CharField(default='', max_length=64, blank=True)),
                ('location_state_name', models.CharField(default='', choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('PUER', 'Puerto Rico')], verbose_name='State', max_length=64, blank=True)),
                ('location_zipcode', models.CharField(default='', verbose_name='Zip', max_length=10, blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessBankAccountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('account_type', models.CharField(default='', verbose_name='Type of Account', max_length=64)),
                ('account_number', models.CharField(default='', max_length=64)),
                ('account_balance', models.PositiveIntegerField(default=0)),
                ('bank_name', models.CharField(default='', max_length=128)),
                ('bank_street', models.CharField(default='', max_length=128, blank=True)),
                ('bank_city', models.CharField(default='', max_length=64, blank=True)),
                ('bank_state_name', models.CharField(default='', choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('PUER', 'Puerto Rico')], verbose_name='Bank State', max_length=64, blank=True)),
                ('bank_zipcode', models.CharField(default='', verbose_name='Bank Zip', max_length=10, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCreditCardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('credit_card', models.CharField(default='', max_length=64)),
                ('merchant_account_number', models.CharField(default='', max_length=64, blank=True)),
                ('bank_name', models.CharField(default='', max_length=128)),
                ('bank_street', models.CharField(default='', max_length=128, blank=True)),
                ('bank_city', models.CharField(default='', max_length=64, blank=True)),
                ('bank_state_name', models.CharField(default='', choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('PUER', 'Puerto Rico')], verbose_name='Bank State', max_length=64, blank=True)),
                ('bank_zipcode', models.CharField(default='', verbose_name='Bank Zip', max_length=10, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientDependent',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('age', models.PositiveIntegerField()),
                ('relationship', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ClientSpouse',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('return_with', models.BooleanField(verbose_name='Is this a return with your Spouse ?')),
                ('first_name', models.CharField(verbose_name='Spouse First Name', max_length=32)),
                ('middle_name', models.CharField(default='', verbose_name='Spouse Middle Name', max_length=32, blank=True)),
                ('last_name', models.CharField(verbose_name='Spouse Last Name', max_length=32)),
                ('ssn', localflavor.us.models.USSocialSecurityNumberField(verbose_name='Social Security Number on IRS Account', max_length=11)),
                ('birthdate', models.DateField(verbose_name='Spouse Birth Date')),
                ('driverlicense', models.CharField(default='', verbose_name="Spouse Driver's License Number and State", max_length=128, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('name', models.CharField(verbose_name='Name of Institution', max_length=128)),
                ('street', models.CharField(default='', max_length=128, blank=True)),
                ('city', models.CharField(default='', max_length=64, blank=True)),
                ('state_name', models.CharField(default='', choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('PUER', 'Puerto Rico')], verbose_name='State', max_length=64, blank=True)),
                ('zipcode', models.CharField(default='', verbose_name='Zip', max_length=10, blank=True)),
                ('account_number', models.CharField(max_length=32)),
                ('credit_limit', models.PositiveIntegerField(default=0)),
                ('amount_owed', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('employer_name', models.CharField(help_text='If your self employed and do not have a business name, write "self"', max_length=64)),
                ('street', models.CharField(default='', max_length=128, blank=True)),
                ('city', models.CharField(default='', max_length=64, blank=True)),
                ('state_name', models.CharField(default='', choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('PUER', 'Puerto Rico')], verbose_name='State', max_length=64, blank=True)),
                ('zipcode', models.CharField(default='', verbose_name='Zip', max_length=10, blank=True)),
                ('phone_work', utils.widgets.PhoneNumberField(default='', verbose_name='Work Phone', max_length=20, blank=True)),
                ('contact_at_work_allowed', models.BooleanField(default=True, verbose_name='Does employer allow contact at work?')),
                ('long_work_years', models.PositiveIntegerField(verbose_name='How long with this employer (Years)')),
                ('long_work_month', models.PositiveIntegerField(verbose_name='How long with this employer (Months)')),
                ('occupation', models.CharField(max_length=128)),
                ('w4extemptions', models.PositiveIntegerField(null=True, default=None, verbose_name='Number of exemptions claimed on Form W-4', help_text='This is only if you are a w-2 wage earner and do not receive a "1099".')),
                ('pay_period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('bi-weekly', 'Bi-Weekly'), ('other', 'Other')], help_text='Indicate if you get paid weekly, biweekly or monthly.', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='F433aPage1',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('first_name', models.CharField(max_length=32)),
                ('middle_name', models.CharField(default='', max_length=32, blank=True)),
                ('last_name', models.CharField(max_length=32)),
                ('ssn', localflavor.us.models.USSocialSecurityNumberField(verbose_name='Social Security Number on IRS Account', max_length=11)),
                ('ein', models.CharField(default='', verbose_name='Employer Identification Number EIN', help_text='This is used if you are operating or receiving income under a separate tax ID number. This can also be a corporate EIN', max_length=32, blank=True, null=True)),
                ('street', models.CharField(default='', max_length=128, blank=True)),
                ('apt', models.CharField(default='', max_length=8, blank=True)),
                ('city', models.CharField(default='', max_length=64, blank=True)),
                ('state_name', models.CharField(default='', choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('PUER', 'Puerto Rico')], verbose_name='State', max_length=64, blank=True)),
                ('zipcode', models.CharField(default='', verbose_name='Zip', max_length=10, blank=True)),
                ('phone_home', utils.widgets.PhoneNumberField(default='', verbose_name='Home Phone', max_length=20, blank=True)),
                ('phone_home_bttc', models.CharField(default='', verbose_name='Home: Best Time to Call', max_length=32, blank=True)),
                ('phone_cell', utils.widgets.PhoneNumberField(default='', verbose_name='Cell Phone', max_length=20, blank=True)),
                ('phone_work', utils.widgets.PhoneNumberField(default='', verbose_name='Work Phone', max_length=20, blank=True)),
                ('phone_work_ext', models.CharField(default='', verbose_name='Work Phone Ext', max_length=6, blank=True)),
                ('phone_work_bttc', models.CharField(default='', verbose_name='Work: Best Time to Call', max_length=32, blank=True)),
                ('phone_work_cell', utils.widgets.PhoneNumberField(default='', verbose_name='Business Cell Phone', max_length=20, blank=True)),
                ('driverlicense', models.CharField(default='', verbose_name="Taxpayer Driver's License Number and State", max_length=128, blank=True)),
                ('birthdate', models.DateField()),
                ('additional_notes', models.TextField(null=True, verbose_name='Additional Info', help_text='Use this space to add any additional information for 433-A, Section 1', blank=True)),
                ('county', models.ForeignKey(to='repository.County')),
            ],
        ),
        migrations.CreateModel(
            name='F433aPage2',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('additional_notes', models.TextField(null=True, verbose_name='Additional Info', help_text='Use this space to add any additional information for 433-A, Section 2', blank=True)),
                ('employment_info', models.OneToOneField(to='irs433a.EmploymentInfo', related_name='page2_as_taxpayer', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='F433aPage3',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('additional_notes', models.TextField(null=True, verbose_name='Additional Info', help_text='Use this space to add any additional information for 433-A, Section 3', blank=True)),
                ('asset_transfer', models.OneToOneField(to='irs433a.AssetTransferDetails', related_name='page', null=True)),
                ('bankruptcy', models.OneToOneField(to='irs433a.BankruptcyInfo', related_name='page', null=True)),
                ('beneficiary', models.OneToOneField(to='irs433a.BeneficiaryInfo', related_name='page', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='F433aPage4',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('cash_on_hand', models.PositiveIntegerField(default=0, help_text='Include cash that is not in a bank. Most people have under $100 "cash"')),
                ('bank_balance_date', models.DateField(null=True, verbose_name='Bank Account Balance As of', help_text='This is the date you are preparing the form', blank=True)),
                ('loan_balance_date', models.DateField(null=True, verbose_name='Loan Balance As of', help_text='This is the date you are preparing the form', blank=True)),
                ('cc_amount_owed_date', models.DateField(verbose_name=' Amount Owed as of', null=True, blank=True)),
                ('cc_available_credit_date', models.DateField(null=True, verbose_name='Available Credit as of', help_text='The IRS trying to determine unused credit that you may still have access to. Generally this section applies to credit cards', blank=True)),
                ('total_cash', models.IntegerField(default=0, help_text='Auto-calculated, correct the amounts from any attachments')),
                ('total_equity', models.IntegerField(default=0, help_text='Auto-calculated, correct the amounts from any attachments')),
                ('total_credit', models.IntegerField(default=0, verbose_name='Total Available Credit', help_text='Auto-calculated, correct the amounts from any attachments')),
                ('total_available_cash', models.IntegerField(default=0, help_text='Auto-calculated, correct the amounts from any attachments')),
                ('banking_additional_info', models.TextField(null=True, help_text='If you have additional checking, online bank accounts, money market accounts, savings accounts, stored value cards (e.g., payroll cards, government benefit cards, etc.) List safe deposit boxes including location and contents, enter the information here', blank=True)),
                ('investment_additional_info', models.TextField(null=True, help_text='If you have additional investments, enter the information here', blank=True)),
                ('credit_additional_info', models.TextField(null=True, help_text='If you have additional credit available, enter the information here', blank=True)),
                ('insurance_additional_info', models.TextField(null=True, help_text='If you have additional Life Insurance, enter the information here', blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='F433aPage5',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('real_property_total_equity', models.PositiveIntegerField(default=0, verbose_name='Total Equity', help_text='Auto-calculated, correct the amounts from any attachments')),
                ('vehicles_total_equity', models.PositiveIntegerField(default=0, verbose_name='Total Equity', help_text='Auto-calculated, correct the amounts from any attachments')),
                ('personal_assets_total_equity', models.PositiveIntegerField(default=0, verbose_name='Total Equity', help_text='Auto-calculated, correct the amounts from any attachments')),
            ],
        ),
        migrations.CreateModel(
            name='F433aPage6',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('wages', models.PositiveIntegerField(default=0, verbose_name='Wages (Taxpayer)', help_text=' Enter gross monthly wages and/or salaries.\nDo not deduct withholding or allotments taken out of pay, such as insurance payments, credit union deductions,\ncar payments, etc. To calculate the gross monthly wages and/or salaries:\nIf paid weekly - multiply weekly gross wages by 4.3. Example: $425.89 x 4.3 = $1,831.33\nIf paid biweekly (every 2 weeks) - multiply biweekly gross wages by 2.17. Example: $972.45 x 2.17 = $2,110.22\nIf paid semimonthly (twice each month) - multiply semimonthly gross wages by 2. Example: $856.23 x 2 = $1,712.46', blank=True)),
                ('wages_spouse', models.PositiveIntegerField(default=0, verbose_name='Wages (Spouse)', help_text=' Enter gross monthly wages and/or salaries.\nDo not deduct withholding or allotments taken out of pay, such as insurance payments, credit union deductions,\ncar payments, etc. To calculate the gross monthly wages and/or salaries:\nIf paid weekly - multiply weekly gross wages by 4.3. Example: $425.89 x 4.3 = $1,831.33\nIf paid biweekly (every 2 weeks) - multiply biweekly gross wages by 2.17. Example: $972.45 x 2.17 = $2,110.22\nIf paid semimonthly (twice each month) - multiply semimonthly gross wages by 2. Example: $856.23 x 2 = $1,712.46', blank=True)),
                ('interest', models.PositiveIntegerField(default=0, verbose_name='Interest (Dividends)', blank=True)),
                ('net_business_income', models.PositiveIntegerField(default=0, verbose_name='Net Business Income', help_text='Enter monthly net business income. This is the amount earned after ordinary and\nnecessary monthly business expenses are paid. This figure is the amount from page 6, line 89. If the net business\nincome is a loss, enter “0”. Do not enter a negative number. If this amount is more or less than previous years,\nattach an explanation.', blank=True)),
                ('net_rental_income', models.PositiveIntegerField(default=0, verbose_name='Net Rental Income', help_text='Enter monthly net rental income. This is the amount earned after ordinary and\nnecessary monthly rental expenses are paid. Do not include deductions for depreciation or depletion.\nIf the net rental income is a loss, enter “0.” Do not enter a negative number.', blank=True)),
                ('distributions', models.PositiveIntegerField(default=0, verbose_name='Distributions', help_text='Enter the total distributions from partnerships and subchapter S corporations\nreported on Schedule K-1, and from limited liability companies reported on Form 1040, Schedule C, D or E.\nEnter total distributions from IRAs if not included under pension income.', blank=True)),
                ('pension', models.PositiveIntegerField(default=0, verbose_name='Pension (Taxpayer)', blank=True)),
                ('pension_spouse', models.PositiveIntegerField(default=0, verbose_name='Pension (Spouse)', blank=True)),
                ('social_security', models.PositiveIntegerField(default=0, verbose_name='Social Security (Taxpayer)', blank=True)),
                ('social_security_spouse', models.PositiveIntegerField(default=0, verbose_name='Social Security (Spouse)', blank=True)),
                ('child_support', models.PositiveIntegerField(default=0, verbose_name='Child Support', blank=True)),
                ('alimony', models.PositiveIntegerField(default=0, verbose_name='Alimony', blank=True)),
                ('other_1_name', models.CharField(null=True, verbose_name='Other Income 1: Description', help_text='Include agricultural subsidies, unemployment compensation, gambling income,\noil credits, rent subsidies, etc.', max_length=64, blank=True)),
                ('other_1', models.PositiveIntegerField(default=0, verbose_name='Other Income 1', blank=True)),
                ('other_2_name', models.CharField(null=True, verbose_name='Other Income 2: Description', help_text='Include agricultural subsidies, unemployment compensation, gambling income,\noil credits, rent subsidies, etc.', max_length=64, blank=True)),
                ('other_2', models.PositiveIntegerField(default=0, verbose_name='Other Income 2', blank=True)),
                ('food_clothing', models.PositiveIntegerField(default=0, verbose_name='Food, Clothing and Misc.', help_text='Total of food, clothing, housekeeping supplies, and personal care products for\none month. The miscellaneous allowance is for expenses incurred that are not included in any other allowable living\nexpense items. Examples are credit card payments, bank fees and charges, reading material, and school supplies.', blank=True)),
                ('housing', models.PositiveIntegerField(default=0, verbose_name='Housing and Utilities', help_text='For principal residence: Total of rent or mortgage payment. Add the average monthly expenses\nfor the following: property taxes, homeowner’s or renter’s insurance, maintenance, dues, fees, and utilities.\nUtilities include gas, electricity, water, fuel, oil, other fuels, trash collection, telephone, cell phone,\ncable television and internet services.', blank=True)),
                ('vehicle_own', models.PositiveIntegerField(default=0, verbose_name='Vehicle Ownership Costs', help_text='Total of monthly lease or purchase/loan payments.', blank=True)),
                ('vehicle_oper', models.PositiveIntegerField(default=0, verbose_name='Vehicle Operating Costs', help_text='Total of maintenance, repairs, insurance, fuel, registrations, licenses, inspections,\nparking, and tolls for one month.', blank=True)),
                ('pub_transport', models.PositiveIntegerField(default=0, verbose_name='Public Transportation', help_text='Total of monthly fares for mass transit (e.g., bus, train, ferry, taxi, etc.)', blank=True)),
                ('health', models.PositiveIntegerField(default=0, verbose_name='Health Insurance', blank=True)),
                ('oop_healthcare', models.PositiveIntegerField(default=0, verbose_name='Out of Pocket Health Care Costs', help_text='Monthly total of medical services, prescription drugs and medical supplies\n(e.g., eyeglasses, hearing aids, etc.)', blank=True)),
                ('court', models.PositiveIntegerField(default=0, verbose_name='Court Ordered Payments', blank=True)),
                ('child_care', models.PositiveIntegerField(default=0, verbose_name='Child/Dependent Care', blank=True)),
                ('life_insurance', models.PositiveIntegerField(default=0, verbose_name='Life Insurance', blank=True)),
                ('taxes', models.PositiveIntegerField(default=0, verbose_name='Taxes (Income and FICA)', help_text='Include state and Federal taxes withheld from salary or wages, or paid as estimated taxes.', blank=True)),
                ('secured_debts', models.PositiveIntegerField(default=0, verbose_name='Secured Debts', blank=True)),
                ('local_taxes', models.PositiveIntegerField(default=0, verbose_name='Delinquent State or Local Taxes', blank=True)),
                ('other_expenses', models.PositiveIntegerField(default=0, verbose_name='Other Expenses', blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='F433aPage7',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('business_name', models.CharField(max_length=128)),
                ('business_street', models.CharField(default='', max_length=128, blank=True)),
                ('business_city', models.CharField(default='', max_length=64, blank=True)),
                ('business_state_name', models.CharField(default='', choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('PUER', 'Puerto Rico')], verbose_name='Business State', max_length=64, blank=True)),
                ('business_zipcode', models.CharField(default='', verbose_name='Business Zip', max_length=10, blank=True)),
                ('ein', models.CharField(default='', verbose_name='Employer Identification Number', null=True, max_length=32, blank=True)),
                ('business_type', models.CharField(verbose_name='Type of Business', max_length=128)),
                ('fed_contractor', models.BooleanField(default=False, verbose_name='Federal Contractor?')),
                ('business_web', models.CharField(verbose_name='Business Website', null=True, max_length=256)),
                ('num_employees', models.PositiveIntegerField(default=0)),
                ('average_gross_monthly_payroll', models.PositiveIntegerField(default=0)),
                ('tax_deposit_freq', models.CharField(verbose_name='Frequency of Tax Deposits', max_length=64)),
                ('bank_balance_date', models.DateField(null=True, verbose_name='Bank Account Balance As of', help_text='This is the date you are preparing the form')),
                ('total_cash_on_hand', models.PositiveIntegerField(default=0, help_text='Include cash that is not in a bank')),
                ('total_cash_in_banks', models.PositiveIntegerField(default=0, help_text='Auto-calculated, correct the amounts from any attachments')),
                ('outstanding_balance', models.PositiveIntegerField(default=0, verbose_name='Total Outstanding Balance', help_text='Auto-calculated, correct the amounts from any attachments')),
                ('total_equity', models.PositiveIntegerField(default=0, help_text='Auto-calculated, correct the amounts from any attachments')),
            ],
        ),
        migrations.CreateModel(
            name='F433aPage8',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('accounting_method', models.BooleanField(default=False, verbose_name='Accounting Method Used', help_text='Use the prior 3, 6, 9 or 12 month period to determine your typical business income and expenses.')),
                ('period_start', models.DateField(verbose_name='Income and Expenses period start date')),
                ('period_end', models.DateField(verbose_name='Income and Expenses period end date')),
                ('gross_receipts', models.PositiveIntegerField(default=0, blank=True)),
                ('gross_rental_income', models.PositiveIntegerField(default=0, blank=True)),
                ('interest', models.PositiveIntegerField(default=0, blank=True)),
                ('dividends', models.PositiveIntegerField(default=0, blank=True)),
                ('cash_receipts_other', models.PositiveIntegerField(default=0, verbose_name='Cash Receipts not included in lines above', blank=True)),
                ('other_1_name', models.CharField(verbose_name='Other Income 1: description', null=True, max_length=64, blank=True)),
                ('other_1_value', models.PositiveIntegerField(default=0, verbose_name='Other Income 1: value', blank=True)),
                ('other_2_name', models.CharField(verbose_name='Other Income 2: description', null=True, max_length=64, blank=True)),
                ('other_2_value', models.PositiveIntegerField(default=0, verbose_name='Other Income 2: value', blank=True)),
                ('other_3_name', models.CharField(verbose_name='Other Income 3: description', null=True, max_length=64, blank=True)),
                ('other_3_value', models.PositiveIntegerField(default=0, verbose_name='Other Income 3: value', blank=True)),
                ('other_4_name', models.CharField(verbose_name='Other Income 4: description', null=True, max_length=64, blank=True)),
                ('other_4_value', models.PositiveIntegerField(default=0, verbose_name='Other Income 4: value', blank=True)),
                ('materials', models.PositiveIntegerField(default=0, verbose_name='Materials Purchased', help_text='Materials are items directly related to the production of a product or service', blank=True)),
                ('inventory', models.PositiveIntegerField(default=0, verbose_name='Inventory Purchased', help_text='Goods bought for resale', blank=True)),
                ('gross_wages_and_salaries', models.PositiveIntegerField(default=0, blank=True)),
                ('rent', models.PositiveIntegerField(default=0)),
                ('supplies', models.PositiveIntegerField(default=0, help_text='Supplies are items used in the business that are consumed or used up within one year. This could be the cost of books, office supplies, professional equipment, etc')),
                ('utilities_telephone', models.PositiveIntegerField(default=0, verbose_name='Utilities/Telephone', help_text='Utilities include gas, electricity, water, oil, other fuels, trash collection, telephone, cell phone and business internet.', blank=True)),
                ('vehicle_suppl', models.PositiveIntegerField(default=0, verbose_name='Vehicle Gasoline/Oil', blank=True)),
                ('maintenance', models.PositiveIntegerField(default=0, verbose_name='Repairs & Maintenance', blank=True)),
                ('insurance', models.PositiveIntegerField(default=0, blank=True)),
                ('taxes', models.PositiveIntegerField(default=0, verbose_name='Current Taxes', help_text='Real estate, excise, franchise, occupational, personal property, sales and employer’s portion of employment taxes', blank=True)),
                ('other_expenses', models.PositiveIntegerField(default=0, verbose_name='Other Expenses, including installment payments', blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Form433a',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('client', models.OneToOneField(to='clients.Client', related_name='form433a')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('name', models.CharField(verbose_name='Name', max_length=128)),
                ('street', models.CharField(default='', max_length=128, blank=True)),
                ('city', models.CharField(default='', max_length=64, blank=True)),
                ('state_name', models.CharField(default='', choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('PUER', 'Puerto Rico')], verbose_name='State', max_length=64, blank=True)),
                ('zipcode', models.CharField(default='', verbose_name='Zip', max_length=10, blank=True)),
                ('policy_number', models.CharField(max_length=32)),
                ('policy_owner', models.CharField(verbose_name='owner of the Policy', max_length=64)),
                ('cash_value', models.PositiveIntegerField(default=0, verbose_name='Current Cash Value')),
                ('loan_balance', models.PositiveIntegerField(default=0, verbose_name='Outstanding Loan Balance')),
                ('formpage', models.ForeignKey(to='irs433a.F433aPage4', related_name='insurances', null=True, related_query_name='insurance')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('investment_type', models.CharField(max_length=32)),
                ('full_name', models.CharField(max_length=128)),
                ('street', models.CharField(default='', max_length=128, blank=True)),
                ('city', models.CharField(default='', max_length=64, blank=True)),
                ('state_name', models.CharField(default='', choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('PUER', 'Puerto Rico')], verbose_name='State', max_length=64, blank=True)),
                ('zipcode', models.CharField(default='', verbose_name='Zip', max_length=10, blank=True)),
                ('phone', utils.widgets.PhoneNumberField(default='', verbose_name='Phone', max_length=20, blank=True)),
                ('current_value', models.PositiveIntegerField(default=0)),
                ('loan_balance', models.PositiveIntegerField(default=0, null=True)),
                ('formpage', models.ForeignKey(to='irs433a.F433aPage4', related_name='investments', null=True, related_query_name='investment')),
            ],
        ),
        migrations.CreateModel(
            name='LawsuitPartyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('is_defendant', models.BooleanField(default=False, verbose_name='Plaintiff or a Defendant?')),
                ('location', models.CharField(verbose_name='Location of Filing', max_length=128)),
                ('representer', models.CharField(verbose_name='Represented by', help_text='Who is the lawyer handling your law suit.', max_length=128)),
                ('case_number', models.CharField(verbose_name='Case Number', max_length=16)),
                ('amount', models.PositiveIntegerField(verbose_name='Amount of Suit', help_text='Many times there is no "demanded" amount. If that is the case, place 0 here')),
                ('completion_date', models.DateField(null=True, verbose_name='Possible Completion Date', help_text='Sometimes, this information is not available or unknown at this time', blank=True)),
                ('subject', models.CharField(verbose_name='Subject of Suit', help_text='What is the cause of action? Ie. car accident, etc', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='LiveAbroadDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('date_from', models.DateField(verbose_name='From')),
                ('date_to', models.DateField(verbose_name='To')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentProcessorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('name', models.CharField(default='', max_length=128)),
                ('account_number', models.CharField(default='', max_length=64)),
                ('street', models.CharField(default='', max_length=128, blank=True)),
                ('city', models.CharField(default='', max_length=64, blank=True)),
                ('state_name', models.CharField(default='', choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('PUER', 'Puerto Rico')], verbose_name='State', max_length=64, blank=True)),
                ('zipcode', models.CharField(default='', verbose_name='Zip', max_length=10, blank=True)),
                ('formpage', models.ForeignKey(to='irs433a.F433aPage7', related_name='paymentprocessors', null=True, related_query_name='paymentprocessor')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalAssetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('market_value', models.PositiveIntegerField(default=0, verbose_name='Current Fair Market Value')),
                ('current_loan_balance', models.PositiveIntegerField(default=0)),
                ('lender_name', models.CharField(default='', max_length=128, blank=True)),
                ('lender_street', models.CharField(default='', max_length=128, blank=True)),
                ('lender_city', models.CharField(default='', max_length=64, blank=True)),
                ('lender_state_name', models.CharField(default='', choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('PUER', 'Puerto Rico')], verbose_name='Lender State', max_length=64, blank=True)),
                ('lender_zipcode', models.CharField(default='', verbose_name='Lender Zip', max_length=10, blank=True)),
                ('lender_phone', utils.widgets.PhoneNumberField(default='', verbose_name='Lender Phone', max_length=20, blank=True)),
                ('monthly_payment', models.PositiveIntegerField(default=0)),
                ('purchase_date', models.DateField(verbose_name='Purchase Lease Date')),
                ('final_payment_date', models.DateField(default=None, verbose_name='Date of final payment', null=True, blank=True)),
                ('description', models.CharField(verbose_name='Property Description', max_length=128)),
                ('location_street', models.CharField(default='', max_length=128, blank=True)),
                ('location_city', models.CharField(default='', max_length=64, blank=True)),
                ('location_state_name', models.CharField(default='', choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('PUER', 'Puerto Rico')], verbose_name='State', max_length=64, blank=True)),
                ('location_zipcode', models.CharField(default='', verbose_name='Zip', max_length=10, blank=True)),
                ('formpage', models.ForeignKey(to='irs433a.F433aPage5', related_name='personalassets', null=True, related_query_name='personalasset')),
                ('location_county', models.ForeignKey(to='repository.County')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RealPropertyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('market_value', models.PositiveIntegerField(default=0, verbose_name='Current Fair Market Value')),
                ('current_loan_balance', models.PositiveIntegerField(default=0)),
                ('lender_name', models.CharField(default='', max_length=128, blank=True)),
                ('lender_street', models.CharField(default='', max_length=128, blank=True)),
                ('lender_city', models.CharField(default='', max_length=64, blank=True)),
                ('lender_state_name', models.CharField(default='', choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('PUER', 'Puerto Rico')], verbose_name='Lender State', max_length=64, blank=True)),
                ('lender_zipcode', models.CharField(default='', verbose_name='Lender Zip', max_length=10, blank=True)),
                ('lender_phone', utils.widgets.PhoneNumberField(default='', verbose_name='Lender Phone', max_length=20, blank=True)),
                ('monthly_payment', models.PositiveIntegerField(default=0)),
                ('purchase_date', models.DateField(verbose_name='Purchase Lease Date')),
                ('final_payment_date', models.DateField(default=None, verbose_name='Date of final payment', null=True, blank=True)),
                ('description', models.CharField(verbose_name='Property Description', max_length=128)),
                ('location_street', models.CharField(default='', verbose_name='Location Street', max_length=128, blank=True)),
                ('location_city', models.CharField(default='', verbose_name='Location City', max_length=64, blank=True)),
                ('location_state_name', models.CharField(default='', choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('PUER', 'Puerto Rico')], verbose_name='Location State', max_length=64, blank=True)),
                ('location_zipcode', models.CharField(default='', verbose_name='Location Zip', max_length=10, blank=True)),
                ('formpage', models.ForeignKey(to='irs433a.F433aPage5', related_name='realproperties', null=True, related_query_name='realproperty')),
                ('location_county', models.ForeignKey(to='repository.County')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SafeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('location', models.CharField(verbose_name='Location (Name, address and box number(s))', max_length=256)),
                ('contents', models.CharField(max_length=256)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TrusteeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('name', models.CharField(verbose_name='Name of the trust', max_length=128)),
                ('ein', models.CharField(default='', verbose_name='EIN', max_length=32, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('market_value', models.PositiveIntegerField(default=0, verbose_name='Current Fair Market Value')),
                ('current_loan_balance', models.PositiveIntegerField(default=0)),
                ('lender_name', models.CharField(default='', max_length=128, blank=True)),
                ('lender_street', models.CharField(default='', max_length=128, blank=True)),
                ('lender_city', models.CharField(default='', max_length=64, blank=True)),
                ('lender_state_name', models.CharField(default='', choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('PUER', 'Puerto Rico')], verbose_name='Lender State', max_length=64, blank=True)),
                ('lender_zipcode', models.CharField(default='', verbose_name='Lender Zip', max_length=10, blank=True)),
                ('lender_phone', utils.widgets.PhoneNumberField(default='', verbose_name='Lender Phone', max_length=20, blank=True)),
                ('monthly_payment', models.PositiveIntegerField(default=0)),
                ('purchase_date', models.DateField(verbose_name='Purchase Lease Date')),
                ('final_payment_date', models.DateField(default=None, verbose_name='Date of final payment', null=True, blank=True)),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('make', models.CharField(max_length=128)),
                ('year', models.PositiveIntegerField()),
                ('model', models.CharField(max_length=128)),
                ('vin', models.CharField(verbose_name='Vehicle Identification Number', max_length=32)),
                ('license_number', models.CharField(verbose_name='License/Tag Number', max_length=32)),
                ('formpage', models.ForeignKey(to='irs433a.F433aPage5', related_name='vehicles', null=True, related_query_name='vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='f433apage8',
            name='form',
            field=models.OneToOneField(to='irs433a.Form433a', related_name='page8'),
        ),
        migrations.AddField(
            model_name='f433apage7',
            name='form',
            field=models.OneToOneField(to='irs433a.Form433a', related_name='page7'),
        ),
        migrations.AddField(
            model_name='f433apage6',
            name='form',
            field=models.OneToOneField(to='irs433a.Form433a', related_name='page6'),
        ),
        migrations.AddField(
            model_name='f433apage5',
            name='form',
            field=models.OneToOneField(to='irs433a.Form433a', related_name='page5'),
        ),
        migrations.AddField(
            model_name='f433apage4',
            name='form',
            field=models.OneToOneField(to='irs433a.Form433a', related_name='page4'),
        ),
        migrations.AddField(
            model_name='f433apage3',
            name='form',
            field=models.OneToOneField(to='irs433a.Form433a', related_name='page3'),
        ),
        migrations.AddField(
            model_name='f433apage3',
            name='lawsuit_party',
            field=models.OneToOneField(to='irs433a.LawsuitPartyInfo', related_name='page', null=True),
        ),
        migrations.AddField(
            model_name='f433apage3',
            name='liveabroad',
            field=models.OneToOneField(to='irs433a.LiveAbroadDetails', related_name='page', null=True),
        ),
        migrations.AddField(
            model_name='f433apage3',
            name='safe',
            field=models.OneToOneField(to='irs433a.SafeDetails', related_name='page', null=True),
        ),
        migrations.AddField(
            model_name='f433apage3',
            name='trustee',
            field=models.OneToOneField(to='irs433a.TrusteeDetails', related_name='page', null=True),
        ),
        migrations.AddField(
            model_name='f433apage2',
            name='form',
            field=models.OneToOneField(to='irs433a.Form433a', related_name='page2'),
        ),
        migrations.AddField(
            model_name='f433apage2',
            name='spouse_employment_info',
            field=models.OneToOneField(to='irs433a.EmploymentInfo', related_name='page2_as_spouse', null=True),
        ),
        migrations.AddField(
            model_name='f433apage1',
            name='form',
            field=models.OneToOneField(to='irs433a.Form433a', related_name='page1'),
        ),
        migrations.AddField(
            model_name='f433apage1',
            name='spouse',
            field=models.OneToOneField(to='irs433a.ClientSpouse', related_name='page', null=True),
        ),
        migrations.AddField(
            model_name='creditinfo',
            name='formpage',
            field=models.ForeignKey(to='irs433a.F433aPage4', related_name='credits', null=True, related_query_name='credit'),
        ),
        migrations.AddField(
            model_name='clientdependent',
            name='formpage',
            field=models.ForeignKey(to='irs433a.F433aPage1', related_name='dependents', null=True, related_query_name='dependent'),
        ),
        migrations.AddField(
            model_name='businesscreditcardinfo',
            name='formpage',
            field=models.ForeignKey(to='irs433a.F433aPage7', related_name='businessccs', null=True, related_query_name='businesscc'),
        ),
        migrations.AddField(
            model_name='businessbankaccountinfo',
            name='formpage',
            field=models.ForeignKey(to='irs433a.F433aPage7', related_name='businessbankaccs', null=True, related_query_name='businessbankacc'),
        ),
        migrations.AddField(
            model_name='businessassetinfo',
            name='formpage',
            field=models.ForeignKey(to='irs433a.F433aPage7', related_name='businessassets', null=True, related_query_name='businessasset'),
        ),
        migrations.AddField(
            model_name='businessassetinfo',
            name='location_county',
            field=models.ForeignKey(to='repository.County'),
        ),
        migrations.AddField(
            model_name='bankaccountinfo',
            name='formpage',
            field=models.ForeignKey(to='irs433a.F433aPage4', related_name='bank_accounts', null=True, related_query_name='bank_account'),
        ),
        migrations.AddField(
            model_name='accountsreceivableinfo',
            name='formpage',
            field=models.ForeignKey(to='irs433a.F433aPage7', related_name='accountsreceivables', null=True, related_query_name='accountsreceivable'),
        ),
    ]
