# -*- coding: utf-8 -*-

"""
    This file contains final aggregated settings for the project.
    Do NOT edit this file manually.
    All changes should be done in files base.py or local.py or /usr/local/etc/irsexpress2.yaml

    Settings get overridden in this order:
    base.py -> (development/production).py -> local.py -> /usr/local/etc/[appname].yaml -> settings.py
    Most secret and server-specific settings should reside in .yaml file.
    Other files are stored in repository
"""

import os
from ..apps.utils.dynsettings import import_settings
from .local import *

import_settings(LOCAL_SETTINGS_FILE)

from .logging_settings import LOGGING, LOG_FOLDER

if DEBUG:
    # make all loggers use the console.
    for logger in LOGGING['loggers']:
        if 'console' not in LOGGING['loggers'][logger]['handlers']:
            LOGGING['loggers'][logger]['handlers'] += ['console']
